trigger:
  - development_1_0
  - release_1_0

name: 1.0$(Rev:.r)


variables:
  - name: IsProd
    value:  $[in(variables['Build.SourceBranch'],'refs/heads/release_1_0')]
  - name: BuildNumber
    value: 1.$(Rev:.r)
    # Common Library
  - group: IOT-SC-GLOBAL

    # Common variables
  - name: SourceCodeRepoName
    value: 'iotsc-tsi-caas'
  - name: RepositoryName
    value: 'iotsc-tsi-caas'

  - name: NonProdACREnvironment
    value: '$(NON-PROD-ACR-ENVIRONMENT)'

  - name: ProdACREnvironment
    value: '$(PROD-ACR-ENVIRONMENT)'

  - name: ACRServiceConnectionNonProd
    value: '$(ACR-SERVICE-CONNECTION-NON-PROD)'

  - name: ACRServiceConnectionProd
    value: '$(ACR-SERVICE-CONNECTION-PROD)'

  - name: ARMSubscriptionNonProd
    value: '$(ARM-SUBSCRIPTION-NON-PROD)'

  - name: ARMSubscriptionProd
    value: '$(ARM-SUBSCRIPTION-PROD)'

stages:
  - stage: BuildStageNonProd
    jobs:
      - job: CodeBuild
        displayName:  'Building for environment non-prod'
        pool:
          name: Azure Pipelines
          vmImage: 'ubuntu-latest'
        steps:
          - template: azure-pipelines-generic-az-hosted-ci.yml
            parameters:
              env: 'non-prod'
              RepositoryName: $(RepositoryName)
              SourceCodeRepoName: $(SourceCodeRepoName)
              ACRServiceConnection: $(ACRServiceConnectionNonProd)
              ACREnvironmentType: $(NonProdACREnvironment)
              ARMSubscription: $(ARMSubscriptionNonProd)


  - stage: BuildStageProd
    condition: and (succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/prod-deployment'))
    jobs:
      - job: CodeBuild
        displayName: 'Building for environment prod'
        pool:
          name: Azure Pipelines
          vmImage: 'ubuntu-20.04'
        steps:
          - template: azure-pipelines-generic-az-hosted-ci.yml
            parameters:
              env: 'prod'
              RepositoryName: $(RepositoryName)
              SourceCodeRepoName: $(SourceCodeRepoName)
              ACRServiceConnection: $(ACRServiceConnectionProd)
              ACREnvironmentType: $(ProdACREnvironment)
              ARMSubscription: $(ARMSubscriptionProd)