parameters:
  - name: adosServiceConnectionName
    type: string
  - name: resourceGroupName
    type: string
  - name: appName
    type: string
  - name: appSlotName
    type: string
  - name: azureMapsAuthUri
    type: string
  - name: azureMapsAuthCredsClientId
    type: string
  - name: azureMapsAuthCredsClientSecret
    type: string
  - name: azureMapsAuthCredsGrantType
    type: string
  - name: azureMapsAuthCredsResource
    type: string

steps:
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: ${{ parameters.adosServiceConnectionName }}
    appType: 'webAppLinux'
    WebAppName: ${{ parameters.appName }}
    deployToSlotOrASE: true
    ResourceGroupName: ${{ parameters.resourceGroupName }}
    SlotName: ${{ parameters.appSlotName }}
    packageForLinux: '$(Pipeline.Workspace)/wca-api-consumer/WCA.Consumer.Api.zip'
    RuntimeStack: 'DOTNETCORE|6.0'
    StartupCommand: 'dotnet WCA.Consumer.Api.dll'
    #AppSettings: 'test1'
    
- task: AzureAppServiceSettings@1
  displayName: Update app settings
  inputs:
    azureSubscription: ${{ parameters.adosServiceConnectionName }}
    appName: ${{ parameters.appName }}
    slotName: ${{ parameters.appSlotName }}
    appSettings: |
      [
        {
          "name": "WCA_ports__http",
          "value": 80,
          "slotSetting": false
        },
        {
          "name": "WCA_ports__https",
          "value": 0,
          "slotSetting": false
        },
        {
          "name": "PORT",
          "value": 80,
          "slotSetting": false
        },
        {
          "name": "WEBSITES_PORT",
          "value": 80,
          "slotSetting": false
        },
        {
          "name": "WCA_ENVIRONMENT",
          "value": "Development",
          "slotSetting": false
        },
        {
          "name": "WCA_UseAd",
          "value": true,
          "slotSetting": false
        },
        {
          "name": "WCA_AzureMapsAuthCredentials__AuthUri",
          "value": "${{ parameters.azureMapsAuthUri }}",
          "slotSetting": false
        },
        {
          "name": "WCA_AzureMapsAuthCredentials__ClientId",
          "value": "${{ parameters.azureMapsAuthCredsClientId }}",
          "slotSetting": false
        },
        {
          "name": "WCA_AzureMapsAuthCredentials__ClientSecret",
          "value": "${{ parameters.azureMapsAuthCredsClientSecret }}",
          "slotSetting": false
        },
        {
          "name": "WCA_AzureMapsAuthCredentials__GrantType",
          "value": "${{ parameters.azureMapsAuthCredsGrantType }}",
          "slotSetting": false
        },
        {
          "name": "WCA_AzureMapsAuthCredentials__Resource",
          "value": "${{ parameters.azureMapsAuthCredsResource }}",
          "slotSetting": false
        }
      ]

# - task: AzureAppServiceManage@0
#   displayName: Swap inactive and active (production) slots
#   condition: and(succeeded(), ne('${{ parameters.appSlotName }}', 'production'))
#   inputs:
#       azureSubscription: ${{ parameters.adosServiceConnectionName }}
#       Action: "Swap Slots"
#       WebAppName: ${{ parameters.appName }}
#       ResourceGroupName: ${{ parameters.resourceGroupName }}
#       SourceSlot: ${{ parameters.appSlotName }}
