apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tsi-caas.fullname" . }}-secrets
type: Opaque
data:
  APP-INSIGHTS-CONNECTION-STRING: {{ .Values.secrets.APP-INSIGHTS-CONNECTION-STRING | b64enc }}
