apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tsi-caas.fullname" . }}-secrets
type: Opaque
data:
  COSMOSDB_CONNECTION_STRING: {{ .Values.secrets.COSMOSDB_CONNECTION_STRING | b64enc }}
  AZURE_STORAGE_ACCESS_KEY: {{ .Values.secrets.AZURE_STORAGE_ACCESS_KEY | b64enc }}
  APPLICATIONINSIGHTS_CONNECTION_STRING: {{ .Values.secrets.APPLICATIONINSIGHTS_CONNECTION_STRING | b64enc }}
  apikey: {{ .Values.secrets.apikey | b64enc }}
  HASH_KEY: {{ .Values.secrets.HASH_KEY | b64enc }}
  
