apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tsi-caas.fullname" . }}-secrets
type: Opaque
data:
  ApplicationInsights__ConnectionString: {{ .Values.secrets.APP_INSIGHTS_CONNECTION_STRING | b64enc }}
