apiVersion: v1
kind: Service
metadata:
  name: active
  labels:
    {{- include "tsi-caas.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpport }}
      targetPort: {{ .Values.service.targethttpport }}
      protocol: TCP
      name: http     
  selector:
    beta: "false"
