{{- $servicefullName := include "tsi-caas.fullname" . -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "{{ $servicefullName }}-virtualservice"
  labels:
    beta: "true"
spec:
  hosts:
  - {{ .Values.ingress.host }}
  gateways:
  - istio-system/http-gateway
  http:
  - name: "default"
    match:
    - uri:
        prefix: {{ .Values.ingress.pathprefix }}
    rewrite:
      uri: {{ .Values.ingress.pathprefix }}
    route:
    - destination:
        port:
          number: {{ .Values.service.httpport }}
        host: {{ $servicefullName }}